export const projects = [
  {
    id: 1,
    title: "Project Title 1",
    des: "Lorem ipsum dolor sit amet consectetur adipiscing elit dignissim, lacinia netus facilisis at placerat mauris sapien, sociosqu sollicitudin lobortis nostra in vestibulum magna.",
    img: "/p1.svg",
    iconLists: [
      "react.svg",
      "/tailwindcss.svg",
      "/typescript.svg",
      "/three.svg",
      "/fm.svg",
    ],
    link: "/ui.earth.com",
  },
  {
    id: 2,
    title: "Project Title 2",
    des: "Lorem ipsum dolor sit amet consectetur adipiscing elit dignissim, lacinia netus facilisis at placerat mauris sapien, sociosqu sollicitudin lobortis nostra in vestibulum magna.",
    img: "/p2.svg",
    iconLists: [
      "/nextjs.svg",
      "/tailwindcss.svg",
      "/typescript.svg",
      "/stream.svg",
      "/c.svg",
    ],
    link: "/ui.yoom.com",
  },
  {
    id: 3,
    title: "Project Title 3",
    des: "Lorem ipsum dolor sit amet consectetur adipiscing elit dignissim, lacinia netus facilisis at placerat mauris sapien, sociosqu sollicitudin lobortis nostra in vestibulum magna.",
    img: "/p3.svg",
    iconLists: [
      "react.svg",
      "/tailwindcss.svg",
      "/typescript.svg",
      "/three.svg",
      "/c.svg",
    ],
    link: "/ui.aiimg.com",
  },
  {
    id: 4,
    title: "Project Title 4",
    des: "Lorem ipsum dolor sit amet consectetur adipiscing elit dignissim, lacinia netus facilisis at placerat mauris sapien, sociosqu sollicitudin lobortis nostra in vestibulum magna.",
    img: "/p4.svg",
    iconLists: [
      "/nextjs.svg",
      "/tailwindcss.svg",
      "/typescript.svg",
      "/three.svg",
      "/gsap.svg",
    ],
    link: "/ui.apple.com",
  },
  {
    id: 5,
    title: "Project Title 5",
    des: "Lorem ipsum dolor sit amet consectetur adipiscing elit dignissim, lacinia netus facilisis at placerat mauris sapien, sociosqu sollicitudin lobortis nostra in vestibulum magna.",
    img: "/p4.svg",
    iconLists: [
      "/nextjs.svg",
      "/tailwindcss.svg",
      "/typescript.svg",
      "/three.svg",
      "/gsap.svg",
    ],
    link: "/ui.apple.com",
  },
  {
    id: 6,
    title: "Project Title 6",
    des: "Lorem ipsum dolor sit amet consectetur adipiscing elit dignissim, lacinia netus facilisis at placerat mauris sapien, sociosqu sollicitudin lobortis nostra in vestibulum magna.",
    img: "/p4.svg",
    iconLists: [
      "/nextjs.svg",
      "/tailwindcss.svg",
      "/typescript.svg",
      "/three.svg",
      "/gsap.svg",
    ],
    link: "/ui.apple.com",
  },
];

export const aboutMe = {
  img: "/about-img.jpeg",
};
